### ISSUE TITLE
Upgrade to latest ng-annotate?

### ISSUE THREAD

**Issue by gylaz** [kikonen/ngannotate-rails#14]
Hi,

I noticed that `ng-annotate` 0.15.4 is out, and this gem is a few versions behind. What do you think about upgrading? I could submit a PR, but I couldn't figure out how the vendored `ngannotate.js` file was generated.

**Comment by kikonen** [comment]
Process of updating is

1) I keep polling ngannotate project every now and then to see if there is any update :)
2) Someone notifies that update is needed, in case (1) fails :)
3) release (not really complicated just few steps, takes only few minutes)

FYI, see readme
```
rake ngannotate:build
```

Anyway, ngannotate-rails-0.15.5 is now pushed to rubygems

**Comment by gylaz** [comment]
That was super fast. Thank you!
