### ISSUE TITLE
Not working with sprocket 3.x

### ISSUE THREAD

**Issue by allaire** [kikonen/ngannotate-rails#16]
See error below:

```ruby
/Users/allaire/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ngannotate-rails-0.15.4/lib/ngannotate/processor.rb:2:in `require': cannot load such file -- sprockets/processor (LoadError)
```

`require 'sprockets/processor'` seems to be the culprit

**Comment by kikonen** [comment]
Q: What version of 3.x exactly? i.e. it should work with 3.2.x at least (*).
Q: What version of sprockets gem you have?

(*) https://github.com/kikonen/ngannotate-rails/tree/master/example

**Comment by kikonen** [comment]
(duh, you said sprockets not rails)

It looks like there is incompatible change in sprockets gem; i.e. "Processor" is moved/renamed into something else.

**Comment by allaire** [comment]
@kikonen Yep, they moved things around.

**Comment by kikonen** [comment]
Could you try this branch and tell how it goes?

Initial sprockets 3.x support: https://github.com/kikonen/ngannotate-rails/pull/17

**Comment by allaire** [comment]
@kikonen Was able to start the app using this branch (foreman is crashing using master), I assume everything should work now :+1:

**Comment by kikonen** [comment]
okey, good, based into my quick testing it should still work also with sprockets 2.x. So we may be then in "good enough" state.

**Comment by allaire** [comment]
Release the kraken!

**Comment by kikonen** [comment]
https://github.com/kikonen/ngannotate-rails/pull/17 should fix thix.

Released as 0.15.4.1

**Comment by jnraine** [comment]
I just hit this bug as well. This release came just in time! :smile_cat:

Thanks guys.

**Comment by djvs** [comment]
Still broken, just in a different way... LoadError: cannot load such file -- sprockets/processor
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/bundler/gems/ngannotate-rails-d8b958910899/lib/ngannotate/processor.rb:2:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/bundler/gems/ngannotate-rails-d8b958910899/lib/ngannotate/rails/railtie.rb:5:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/bundler/gems/ngannotate-rails-d8b958910899/lib/ngannotate/rails.rb:2:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2/bundler/gems/ngannotate-rails-d8b958910899/lib/ngannotate.rb:8:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.2/bundler/gems/ngannotate-rails-d8b958910899/lib/ngannotate-rails.rb:1:in `require_relative'
/home/ubuntu/.rvm/gems/ruby-2.1.2/bundler/gems/ngannotate-rails-d8b958910899/lib/ngannotate-rails.rb:1:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
/home/ubuntu/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'

**Comment by kikonen** [comment]
"Still"? Err... if it's failing one year later with different issue doent exactly sound so to me... :)

**Comment by djvs** [comment]
Same dependency which can't be met, so semi related I suppose

**Comment by kikonen** [comment]
Ack

**Comment by kikonen** [comment]
Okey, "Ngannotate#sprockets_v3?" Version detect is now failing. What version of sprockets you have?

**Comment by djvs** [comment]
I had to change it back last night to get a site back up on production, but I'm 95% sure it was locked at 3.0.0.

**Comment by kikonen** [comment]
This should match that, strange

```ruby
module Ngannotate
  def self.sprockets_v3?
    gem = Gem.loaded_specs['sprockets']
    !(gem.version.to_s =~ /\A3\..*\z/).nil?
  end
end
```

**Comment by djvs** [comment]
I'll double check later tonight

**Comment by kikonen** [comment]
changed test otherway around to test v2 instead of v3....
