### ISSUE TITLE
Rails server - ng-skip *.es6 files and slowness 

### ISSUE THREAD

**Issue by bradgreens** [kikonen/ngannotate-rails#24]
I'm using BabelJs / Sprockets ES6. My project consists of around 80 `*.es6` files. When I include the ngannotate-rails gem and start up the rails server, in the terminal I can see `ng-skip` being called on *every* ES6 file, and it takes about a second per file.

The result is the first page load takes well over a minute. Any advice - am I missing something?

**Comment by kikonen** [comment]
Sounds a bit strange that just check for skip would be so slow. But need to look into it.

**Comment by bradgreens** [comment]
If it's of any help, here's my Gemfile:

```
source 'https://rubygems.org'
ruby '2.1.4'

gem 'rails', '4.1.12'
gem 'unicorn'
gem 'rake'

gem 'airbrake'
gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'execjs'
gem 'gctools'
gem 'ngannotate-rails'
gem 'oj'
gem 'rails_karma'
gem 'rest_client'
gem 'sass-rails'
gem 'slim'
gem 'sprockets'
gem 'sprockets-es6'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capistrano', '~> 3.2.0', require: false
  gem 'capistrano-bundler', '~> 1.1.2', require: false
  gem 'capistrano-rails', '~> 1.1.3', require: false
  gem 'capistrano-resque', require: false
  gem 'capistrano-rvm', require: false
  gem 'capistrano-unicorn', require: false
  gem 'crack', require: false
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-livereload'
  gem 'spring'
  gem 'tinder', require: false
end

group :development, :test do
  gem 'jasmine-rails'
  gem 'rake-hooks'
  gem 'rspec-rails'
end
```

**Comment by kikonen** [comment]
"ng-skip: <filename>" traces indicate that file is ignored from processing. That check definitely shouldn't be taking long time.

Q: Are you sure that this time is not actually taken by ES6 => ES5 conversion done by babel?

**Comment by bradgreens** [comment]
It's possibly it's taken by the ES6 => ES5 conversion. But I guess that confuses me, when I see ng-skip I'd expect the file to be ignored from processing, but all these files are still getting processed (they have to be, otherwise the JS wouldn't execute in the browser).

Perhaps I'm confused about the terminal output but it's behaving correctly.

**Comment by kikonen** [comment]
In development mode ngannotate processing is by default akipping files, since there is no need for processing (since js file obfuscation is not done).

Tip: When you are not debugging in js side, then you can speed up pages via turning off assets debug in config/environments/development.rb (rails server restart naturally required).

**Comment by kikonen** [comment]
For babel using different js runtime (i.e. perhaps faster?) may also help

Aka.
https://github.com/kikonen/host/blob/master/Gemfile#L17

**Comment by kikonen** [comment]
Be aware also that binding_of_caller gem can also slow things down a bit.

See https://github.com/banister/binding_of_caller/issues/37

**Comment by bradgreens** [comment]
Sounds good, I'll poke around and close this in a bit

**Comment by bradgreens** [comment]
I checked it out, and turning off asset debugging was the ideal solution.

In `config/environments/development.rb`, I simply commented out `config.assets.debug = true`.

Thanks for the tips :beer:
