### ISSUE TITLE
Slow down first request on Heroku

### ISSUE THREAD

**Issue by phuongnd08** [kikonen/ngannotate-rails#27]
When deployed on heroku, the first request invoked all the "ng-process" thingies, cause a very slow boot. I'm not sure how to disable this. Look like a weird mixed effect with the serve static assets plugin on heroku.

**Comment by kikonen** [comment]
Are you sure that app assets are precompiled and production server is not set to compile assets on demand?

**Comment by phuongnd08** [comment]
The asset is precompiled for sure. I don't know about "server is not set to compile assets on demand?". Shouldn't it compile anything as they are already precompiled?

**Comment by kikonen** [comment]
Check config/environments/production.rb

**Comment by phuongnd08** [comment]
We use this https://gist.github.com/phuongnd08/4f3d7ee007f11d071fb9839778ae473e
Together with the rails_12factor gem to serve assets on heroku

**Comment by kikonen** [comment]
Likely that issue relates into https://github.com/heroku/rails_12factor you mentioned. I have no experience about that hack, but since it applies some "magic" over assets, I wouldnt be surprised that it somehow conflicts with normal aasets precompiling logic asumptions.

**Comment by phuongnd08** [comment]
AFAIK, the relevant part should be the that config `config.serve_static_assets = true` that the gem patched over the production configuration. Is there is a way to prevent `ng-process` from being invoked when the assets already exists and `config.serve_static_assets` is set to `true`?

**Comment by kikonen** [comment]
If precompiled assets exist then I would not expect assets pipeline to do processing for them. It should be just serving precompiled js package. Also compile should not happen since it's turned off in env config file.

**Comment by phuongnd08** [comment]
Would you be interested in a small repo that can be deployed to heroku to demonstrate the issue? I'll be happy to create the repo if you have time to have a look.

**Comment by kikonen** [comment]
That's good idea.

**Comment by phuongnd08** [comment]
After upgrade our rails version to 4.2.6 (and ngannotate-rails from 1.2.1 to 1.2.2), the issue gone away. Thank you.
